/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Hello world function - test the napi binding */
export declare function hello(name: string): string
/**
 * Execute a SQL statement (INSERT, UPDATE, DELETE, CREATE, etc.)
 * Returns the number of rows affected, or throws on error
 */
export declare function execute(sql: string): number
/**
 * Query and return results as Arrow IPC stream buffer (zero-copy to JS)
 * Use apache-arrow in JS to read: `tableFromIPC(buffer)`
 */
export declare function query(sql: string): Buffer
